### ISSUE TITLE
Build target django fails for Python 3.6

### ISSUE THREAD

**Issue by hendrikmaus** [pybee/beeware#1]
Beeware fails when trying to build the django target with Python 3.6:

```
$ beeware build django
Running Briefcase...
>>> python setup.py django

running django
 * Writing application template...
There is no branch for Python version '3.6' (existing branches:  3.4, 3.5, master).
Directory /Users/hendrikmaus/.cookiecutters/Python-Django-template isn't a valid template (no cookiecutter.json found).
```

**Comment by freakboy3742** [comment]
Thanks for the report. I've just pushed an initial template for Django under Python 3.6, based on the current 3.5 template - there shouldn't be any changes required from Python 3.5, but if you have any problems, please report them.
