### ISSUE TITLE
It is installing kivy every time I build while it already installed

### ISSUE THREAD

**Issue by krishnaTORQUE** [pybee/beeware#11]
It is installing kivy every time I build while it already installed

**Comment by freakboy3742** [comment]
That seems unlikely, give Kivy is a entirely separate project to BeeWare. 

However, as with your recent report on VOC, you've provided exactly *zero* information about what you were doing, so it's impossible to provide any assistance.

If you want us to help you, you have to help us to help you. A one line statement of the problem you've received doesn't help us do that. We need to know what you were trying to do, what you expected, what you observed... and we need *specifics*, not vague catch-all statements like "I got an error".
