### ISSUE TITLE
Installing beeware fails to pip install on Windows 10/Python 3.7

### ISSUE THREAD

**Issue by jlgimeno** [pybee/beeware#8]
Attempted to pip install beeware into a fresh virtual enviroment in Windows.  Package pythonnet fails to install, pythonnet's docs state it works with Python<=3.6.  Botocore 1.12.26 also failed to install, shows it requires urllib3<1.24,>=1.20, but urllib3 1.24 is installed which fails.

**Comment by freakboy3742** [comment]
This wasn't just Windows specific - it was a problem with the packaging of botocore. I pushed out an updated version of briefcase that should address this problem. 

Closing this ticket on that basis; If you are still able to reproduce the problem, please let me know.
